plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

repositories {
    maven {
        url "https://maven.terraformersmc.com/releases"
        content {
            includeGroup "com.terraformersmc"
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation project(":common")
    implementation "com.terraformersmc:modmenu:${modmenu_version}"
    implementation "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${fcap_version}"
	compileOnly "curse.maven:glitchcore-955399:${glitchcore_fabric_version}" //serene seasons dependency
    implementation "curse.maven:kiwi-549404:${kiwi_fabric_version}" //snow real magic dependency
	implementation "curse.maven:moonrise-1096335:${moonrise_fabric_version}"
	compileOnly "curse.maven:serene-seasons-291874:${serene_seasons_fabric_version}"
    implementation "curse.maven:snow-real-magic-560441:${snow_real_magic_fabric_version}"
}

loom {
    accessWidenerPath.set(project(':common').file("src/main/resources/${mod_id}.classtweaker"))

    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir("${run_dir}/client")
        }

        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir("${run_dir}/server")
        }
    }
}

jar {
    exclude("META-INF/accesstransformer.cfg")
}

tasks.withType(JavaCompile).configureEach {
    source(project(":common").sourceSets.main.allSource)
}

processResources {
    from project(":common").sourceSets.main.resources
}
