# Project
group=bl4ckscor3.mod.snowundertrees
version=1.6
minecraft_version=26.1.2
minecraft_min_version=26.1
java_version=25
license=MIT
mod_id=snowundertrees
mod_name=Snow Under Trees
description=Adds snow under trees in snowy biomes.
mod_author=bl4ckscor3
source_link=https://github.com/bl4ckscor3/SnowUnderTrees
cf_link=https://www.curseforge.com/minecraft/mc-mods/snow-under-trees

# Common
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1
mdg_version=2.0.141
fcap_version=26.1.4
run_dir=../runs
mixin_version=0.13.3+mixin.0.8.5
mixinextras_version=0.3.5

# NeoForge
neoforge_version=26.1.2.76
neoforge_min_version=26.1
glitchcore_neoforge_version=8109770
kiwi_neoforge_version=8087088
moonrise_neoforge_version=7956089
serene_seasons_neoforge_version=8174222
snow_real_magic_neoforge_version=4769110

# Fabric
loom_version=1.16-SNAPSHOT
fabric_version=0.149.0+26.1.2
fabric_loader_version=0.19.2
modmenu_version=18.0.0-alpha.8
glitchcore_fabric_version=8109769
kiwi_fabric_version=7964588
moonrise_fabric_version=7956090
serene_seasons_fabric_version=8174223
snow_real_magic_fabric_version=8162823

# Gradle
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false
