modLoader="javafml"
loaderVersion="[44,)"
license="MIT https://github.com/bl4ckscor3/SnowUnderTrees/blob/1.19/LICENSE"

[[mods]]
	modId="snowundertrees"
	version="${file.jarVersion}"
	displayName="Snow Under Trees"
	description='''Adds snow under trees in snowy biomes.'''
	issueTrackerURL="https://github.com/bl4ckscor3/SnowUnderTrees"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/snow-under-trees"
	authors="bl4ckscor3"

[[dependencies.snowundertrees]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.snowundertrees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"