modLoader="javafml"
loaderVersion="[46,)"
license="MIT https://github.com/bl4ckscor3/SnowUnderTrees/blob/1.20/LICENSE"

[[mods]]
	modId="snowundertrees"
	version="${file.jarVersion}"
	displayName="Snow Under Trees"
	description='''Adds snow under trees in snowy biomes.'''
	issueTrackerURL="https://github.com/bl4ckscor3/SnowUnderTrees"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/snow-under-trees"
	authors="bl4ckscor3"

[[dependencies.snowundertrees]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.snowundertrees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"