modLoader="javafml"
loaderVersion="[1,)"
license="MIT https://github.com/bl4ckscor3/SnowUnderTrees/blob/1.20.6/LICENSE"

[[mods]]
	modId="snowundertrees"
	version="${file.jarVersion}"
	displayName="Snow Under Trees"
	description='''Adds snow under trees in snowy biomes.'''
	issueTrackerURL="https://github.com/bl4ckscor3/SnowUnderTrees"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/snow-under-trees"
	authors="bl4ckscor3"

[[dependencies.snowundertrees]]
    modId="neoforge"
    type="required"
    versionRange="[20.6-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.snowundertrees]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6,1.21)"
    ordering="NONE"
    side="BOTH"