plugins {
    id 'net.neoforged.moddev' version "${mdg_version}"
}

neoForge {
    version = neoforge_version
    accessTransformers = project(":common").files('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        configureEach {
            gameDirectory = mkdir(file("${run_dir}/" + name))
            logLevel = org.slf4j.event.Level.DEBUG
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }

        client {
            client()
        }

        server {
            server()
            programArgument('-nogui')
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    compileOnly project(":common")
    implementation "curse.maven:glitchcore-955399:${glitchcore_neoforge_version}" //serene seasons dependency
	compileOnly "curse.maven:kiwi-303657:${kiwi_neoforge_version}" //snow real magic dependency
    implementation "curse.maven:moonrise-1096335:${moonrise_neoforge_version}"
    implementation "curse.maven:serene-seasons-291874:${serene_seasons_neoforge_version}"
	compileOnly "curse.maven:snow-real-magic-308663:${snow_real_magic_neoforge_version}"
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

jar {
    exclude("${mod_id}.classtweaker")
}

compileJava {
    source(project(":common").sourceSets.main.allSource)
}

processResources {
    from project(":common").sourceSets.main.resources
}